### ISSUE TITLE
Dolls dont work in folia, every command i enter gives internal errors

### ISSUE THREAD

**Issue by bovinespongiformflu** [sjavi4/PlayerDoll#14]
basically on folia, i can create and remove dolls however attempting to set anything just shows a server error.

[00:02:45] [Region Scheduler Thread #2/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'playerdoll:doll' in plugin PlayerDoll v1.19.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:1032) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[folia-1.20.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2259) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2219) ~[?:?]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1516) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:402) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.2.jar:git-Folia-"1e5e215"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getName()" because "doll" is null
	at me.autobot.playerdoll.InvMenu.Menus.Settingmenu.createInventory(Settingmenu.java:36) ~[PlayerDoll-1.19.1.jar:?]
	at me.autobot.playerdoll.InvMenu.InvInitializer.<init>(InvInitializer.java:23) ~[PlayerDoll-1.19.1.jar:?]
	at me.autobot.playerdoll.InvMenu.Menus.Settingmenu.<init>(Settingmenu.java:31) ~[PlayerDoll-1.19.1.jar:?]
	at me.autobot.playerdoll.Command.SubCommands.Set.<init>(Set.java:13) ~[PlayerDoll-1.19.1.jar:?]
	at me.autobot.playerdoll.Command.CommandType$22.execute(CommandType.java:336) ~[PlayerDoll-1.19.1.jar:?]
	at me.autobot.playerdoll.Command.CommandHelper.onCommand(CommandHelper.java:31) ~[PlayerDoll-1.19.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[folia-api-1.20.2-R0.1-SNAPSHOT.jar:?]

on the game screen it just shows an internal error.

**Comment by sjavi4** [comment]
This is a known Issue, which OP will bypass all Doll Online Status check when Command, it will be fixed in next update.
Most of the commands are required Doll to be online, except Create, Spawn, Remove, Rename, Give

**Comment by sjavi4** [comment]
Please check [1.20](https://modrinth.com/plugin/playerdoll/version/1.20)
