### ISSUE TITLE
Bedrock players connected via Geyser-floodgate unable to spawn Dolls

### ISSUE THREAD

**Issue by L-the-forgettable** [sjavi4/PlayerDoll#17]
Steps to reproduce:
1. Join server on bedrock edition of minecraft via Geyser + Floodgate plugins
2. Create new doll
3. Attempt to spawn doll

Expected result: Doll gets spawned without issue
Actual result: Server bails out, doll isn't spawned

**Comment by L-the-forgettable** [comment]
[08:06:09] [Server thread/INFO]: _Lumine_Vekard issued server command: /doll create doll_name
[08:06:09] [Server thread/WARN]: Could not get skin data from session servers!
[08:06:09] [Server thread/WARN]: java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/_Lumine_Vekard
[08:06:09] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
[08:06:09] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[08:06:09] [Server thread/WARN]: 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[08:06:09] [Server thread/WARN]: 	at java.base/java.net.URL.openStream(URL.java:1161)
[08:06:09] [Server thread/WARN]: 	at me.autobot.playerdoll.Command.SubCommands.Create.<init>(Create.java:90)
[08:06:09] [Server thread/WARN]: 	at me.autobot.playerdoll.Command.CommandType$3.execute(CommandType.java:56)
[08:06:09] [Server thread/WARN]: 	at me.autobot.playerdoll.Command.CommandHelper.onCommand(CommandHelper.java:32)
[08:06:09] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[08:06:09] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[08:06:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:875)
[08:06:09] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[08:06:09] [Server thread/WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:413)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:335)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:322)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1856)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1818)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
[08:06:09] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1191)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1170)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1163)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1147)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1060)
[08:06:09] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[08:06:09] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:06:16] [Server thread/INFO]: _Lumine_Vekard issued server command: /doll spawn doll_name
[08:06:16] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[08:06:16] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
[08:06:16] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[08:06:16] [Server thread/WARN]: 	at me.autobot.playerdoll.Dolls.DollHelper.callSpawn(DollHelper.java:19)
[08:06:16] [Server thread/WARN]: 	at me.autobot.playerdoll.Command.SubCommands.Spawn.<init>(Spawn.java:77)
[08:06:16] [Server thread/WARN]: 	at me.autobot.playerdoll.Command.CommandType$25.execute(CommandType.java:379)
[08:06:16] [Server thread/WARN]: 	at me.autobot.playerdoll.Command.CommandHelper.onCommand(CommandHelper.java:32)
[08:06:16] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[08:06:16] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[08:06:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:875)
[08:06:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[08:06:16] [Server thread/WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.a(SourceFile:29)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(SourceFile:13)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.a(SourceFile:8)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.a(SourceFile:8)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.commands.execution.ExecutionContext.a(SourceFile:107)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:413)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:335)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:322)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1856)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1818)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
[08:06:16] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1191)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1170)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1163)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1147)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1060)
[08:06:16] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[08:06:16] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:06:16] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "org.bukkit.configuration.ConfigurationSection.getString(String)" is null
[08:06:16] [Server thread/WARN]: 	at me.autobot.playerdoll.Dolls.IDoll.setSkin(IDoll.java:88)
[08:06:16] [Server thread/WARN]: 	at me.autobot.playerdoll.v1_20_R3.Dolls.AbstractDoll.<init>(AbstractDoll.java:75)
[08:06:16] [Server thread/WARN]: 	at me.autobot.playerdoll.v1_20_R3.Dolls.SpigotDollImpl.<init>(SpigotDollImpl.java:12)
[08:06:16] [Server thread/WARN]: 	at me.autobot.playerdoll.v1_20_R3.Dolls.AbstractDoll.callSpawn(AbstractDoll.java:58)
[08:06:16] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[08:06:16] [Server thread/WARN]: 	... 35 more

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/commit/91f7241424203b5b7341425729aca3f28e683a69

Please check v1.21(https://modrinth.com/plugin/playerdoll/version/1.21) to see if the problem has fixed or not.

**Comment by L-the-forgettable** [comment]
This problem appears to have been fixed
