### ISSUE TITLE
folia error

### ISSUE THREAD

**Issue by xiaoluofa** [sjavi4/PlayerDoll#21]
[14:40:25] [Region Scheduler Thread #5/INFO]: YSieldTrEnGths issued server command: /doll spawn 123
[14:40:25] [Region Scheduler Thread #4/INFO]: -123[local] logged in with entity id 37912938 at ([world]24036.249688673994, 63.0, 27398.394567061954)
[14:40:31] [Region Scheduler Thread #4/WARN]: Riffraff_tt moved wrongly!
[14:40:44] [Region Scheduler Thread #2/WARN]: Riffraff_tt moved wrongly!
[14:40:46] [Region Scheduler Thread #0/WARN]: Riffraff_tt moved wrongly!
[14:40:47] [Region Scheduler Thread #3/ERROR]: [io.papermc.paper.threadedregions.ThreadedRegionizer] Failed to acquire region ThreadedRegion{state=3,sectionCount=133,sections=[RegionSection{sectionCoordinate=[15, -4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=184199752},RegionSection{sectionCoordinate=[15, 0],chunkCount=240,chunksBitset=ffffffffffff0000ffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=6,hash=1055704210},RegionSection{sectionCoordinate=[14, -3],chunkCount=48,chunksBitset=0007000700070007000700070007000700070007000700070007000700070007,nonEmptyNeighbours=5,hash=19798873},RegionSection{sectionCoordinate=[19, 3],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=2028311031},RegionSection{sectionCoordinate=[25, 2],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=794202040},RegionSection{sectionCoordinate=[10, -1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=2001082004},RegionSection{sectionCoordinate=[11, -3],chunkCount=160,chunksBitset=ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0,nonEmptyNeighbours=5,hash=113455094},RegionSection{sectionCoordinate=[17, 4],chunkCount=159,chunksBitset=ffffffffffffffffffffffffffffffff000000007fffffff0000000000000000,nonEmptyNeighbours=5,hash=1383955696},RegionSection{sectionCoordinate=[12, -5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1238176328},RegionSection{sectionCoordinate=[22, 2],chunkCount=224,chunksBitset=fffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffc,nonEmptyNeighbours=5,hash=251154259},RegionSection{sectionCoordinate=[24, 4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=299593189},RegionSection{sectionCoordinate=[14, 2],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=687348178},RegionSection{sectionCoordinate=[21, 2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=151392727},RegionSection{sectionCoordinate=[15, -5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1162368371},RegionSection{sectionCoordinate=[11, -2],chunkCount=160,chunksBitset=ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0ffc0,nonEmptyNeighbours=5,hash=263629946},RegionSection{sectionCoordinate=[19, 0],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1734873815},RegionSection{sectionCoordinate=[10, -4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1582903108},RegionSection{sectionCoordinate=[17, -1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1505561137},RegionSection{sectionCoordinate=[27, -2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1674749952},RegionSection{sectionCoordinate=[25, 1],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1150017543},RegionSection{sectionCoordinate=[18, 3],chunkCount=240,chunksBitset=7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff,nonEmptyNeighbours=5,hash=1396688093},RegionSection{sectionCoordinate=[26, 0],chunkCount=112,chunksBitset=007f007f007f007f007f007f007f007f007f007f007f007f007f007f007f007f,nonEmptyNeighbours=5,hash=1650634761},RegionSection{sectionCoordinate=[21, -1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=344360685},RegionSection{sectionCoordinate=[14, 5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=148609444},RegionSection{sectionCoordinate=[13, 3],chunkCount=32,chunksBitset=c000c000c000c000c000c000c000c000c000c000c000c000c000c000c000c000,nonEmptyNeighbours=5,hash=253155234},RegionSection{sectionCoordinate=[14, 3],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=572711857},RegionSection{sectionCoordinate=[21, 3],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1438121220},RegionSection{sectionCoordinate=[16, 4],chunkCount=160,chunksBitset=ffffffffffffffffffffffffffffffff00000000ffffffff0000000000000000,nonEmptyNeighbours=5,hash=1965467825},RegionSection{sectionCoordinate=[14, -2],chunkCount=48,chunksBitset=0007000700070007000700070007000700070007000700070007000700070007,nonEmptyNeighbours=5,hash=1278528112},RegionSection{sectionCoordinate=[15, 2],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=2034140972},RegionSection{sectionCoordinate=[10, -2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=327883474},RegionSection{sectionCoordinate=[19, 1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1403542322},RegionSection{sectionCoordinate=[19, 5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1947604261},RegionSection{sectionCoordinate=[24, 3],chunkCount=192,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000,nonEmptyNeighbours=5,hash=967146621},RegionSection{sectionCoordinate=[11, -5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=883923842},RegionSection{sectionCoordinate=[26, 1],chunkCount=112,chunksBitset=007f007f007f007f007f007f007f007f007f007f007f007f007f007f007f007f,nonEmptyNeighbours=5,hash=2142849615},RegionSection{sectionCoordinate=[23, -2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1859780417},RegionSection{sectionCoordinate=[12, -4],chunkCount=96,chunksBitset=00000000000000000000000000000000ffffffff00000000ffffffffffffffff,nonEmptyNeighbours=5,hash=2089623667},RegionSection{sectionCoordinate=[25, 4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=884398059},RegionSection{sectionCoordinate=[12, 1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=31983616},RegionSection{sectionCoordinate=[23, 1],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=543870091},RegionSection{sectionCoordinate=[18, 0],chunkCount=209,chunksBitset=7fff007f007f00007fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff,nonEmptyNeighbours=3,hash=905051725},RegionSection{sectionCoordinate=[12, 0],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=5,hash=930774679},RegionSection{sectionCoordinate=[17, 2],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1981007984},RegionSection{sectionCoordinate=[24, -2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=7036077},RegionSection{sectionCoordinate=[24, -1],chunkCount=144,chunksBitset=0000000000000000ffff000000000000ffffffffffffffffffffffffffffffff,nonEmptyNeighbours=5,hash=986892667},RegionSection{sectionCoordinate=[27, 0],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1580766832},RegionSection{sectionCoordinate=[13, -2],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=914396559},RegionSection{sectionCoordinate=[22, 1],chunkCount=224,chunksBitset=fffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffc,nonEmptyNeighbours=5,hash=1817455046},RegionSection{sectionCoordinate=[13, 4],chunkCount=1,chunksBitset=0000000000008000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1088531494},RegionSection{sectionCoordinate=[22, 0],chunkCount=224,chunksBitset=fffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffc,nonEmptyNeighbours=5,hash=1517304156},RegionSection{sectionCoordinate=[27, 3],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1752101744},RegionSection{sectionCoordinate=[15, -3],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=632946082},RegionSection{sectionCoordinate=[16, 1],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1752495535},RegionSection{sectionCoordinate=[21, 4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=857049892},RegionSection{sectionCoordinate=[12, 5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=754912069},RegionSection{sectionCoordinate=[15, 5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1220490765},RegionSection{sectionCoordinate=[10, -3],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1187100565},RegionSection{sectionCoordinate=[17, 3],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=156756847},RegionSection{sectionCoordinate=[23, 4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=377753034},RegionSection{sectionCoordinate=[13, -5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1123391868},RegionSection{sectionCoordinate=[26, 2],chunkCount=112,chunksBitset=007f007f007f007f007f007f007f007f007f007f007f007f007f007f007f007f,nonEmptyNeighbours=5,hash=163836840},RegionSection{sectionCoordinate=[14, -1],chunkCount=21,chunksBitset=0007000700070007000000070007000700000000000000000000000000000000,nonEmptyNeighbours=6,hash=1064922476},RegionSection{sectionCoordinate=[14, 4],chunkCount=120,chunksBitset=fff8fffeffffffffff80ffe0ffe0fff800000000ff00ff000000000000000000,nonEmptyNeighbours=5,hash=153472276},RegionSection{sectionCoordinate=[15, -2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1744145205},RegionSection{sectionCoordinate=[16, 3],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1908243152},RegionSection{sectionCoordinate=[23, -1],chunkCount=144,chunksBitset=0000000000000000ffff000000000000ffffffffffffffffffffffffffffffff,nonEmptyNeighbours=5,hash=98270086},RegionSection{sectionCoordinate=[12, 2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=582044484},RegionSection{sectionCoordinate=[19, -1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1767297028},RegionSection{sectionCoordinate=[18, 5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1160269011},RegionSection{sectionCoordinate=[27, 1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1931959300},RegionSection{sectionCoordinate=[25, -2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=763236013},RegionSection{sectionCoordinate=[13, -4],chunkCount=96,chunksBitset=00000000000000000000000000000000ffffffff00000000ffffffffffffffff,nonEmptyNeighbours=5,hash=96312109},RegionSection{sectionCoordinate=[17, 0],chunkCount=240,chunksBitset=ffffffffffff0000ffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=5,hash=1513401710},RegionSection{sectionCoordinate=[18, 1],chunkCount=240,chunksBitset=7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff,nonEmptyNeighbours=5,hash=322571600},RegionSection{sectionCoordinate=[15, 3],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1315726076},RegionSection{sectionCoordinate=[13, 0],chunkCount=11,chunksBitset=00000000000000000000000000000000c000800000000000c000c000c000c000,nonEmptyNeighbours=6,hash=660733167},RegionSection{sectionCoordinate=[25, -1],chunkCount=144,chunksBitset=0000000000000000ffff000000000000ffffffffffffffffffffffffffffffff,nonEmptyNeighbours=5,hash=1480686256},RegionSection{sectionCoordinate=[23, 3],chunkCount=192,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000,nonEmptyNeighbours=5,hash=466791525},RegionSection{sectionCoordinate=[14, 1],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=914638433},RegionSection{sectionCoordinate=[25, 3],chunkCount=192,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffff0000000000000000,nonEmptyNeighbours=5,hash=506090202},RegionSection{sectionCoordinate=[15, -1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=5,hash=1307389781},RegionSection{sectionCoordinate=[10, -5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1129448201},RegionSection{sectionCoordinate=[16, -1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1467081292},RegionSection{sectionCoordinate=[19, 4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=453105402},RegionSection{sectionCoordinate=[19, 2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1060296008},RegionSection{sectionCoordinate=[26, 4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1814811628},RegionSection{sectionCoordinate=[24, 0],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=881868711},RegionSection{sectionCoordinate=[12, -1],chunkCount=112,chunksBitset=ffffffffffffffff0000ffffffffffff00000000000000000000000000000000,nonEmptyNeighbours=6,hash=565418441},RegionSection{sectionCoordinate=[21, -2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=142774306},RegionSection{sectionCoordinate=[11, 0],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=973375085},RegionSection{sectionCoordinate=[13, 5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=257751949},RegionSection{sectionCoordinate=[12, -3],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=849102462},RegionSection{sectionCoordinate=[11, -4],chunkCount=60,chunksBitset=00000000000000000000000000000000ffc0ffc000000000ffc0ffc0ffc0ffc0,nonEmptyNeighbours=3,hash=771998607},RegionSection{sectionCoordinate=[12, 4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=816451532},RegionSection{sectionCoordinate=[24, 2],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1480727239},RegionSection{sectionCoordinate=[13, 1],chunkCount=32,chunksBitset=c000c000c000c000c000c000c000c000c000c000c000c000c000c000c000c000,nonEmptyNeighbours=5,hash=138217479},RegionSection{sectionCoordinate=[22, -2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=949140788},RegionSection{sectionCoordinate=[15, 4],chunkCount=160,chunksBitset=ffffffffffffffffffffffffffffffff00000000ffffffff0000000000000000,nonEmptyNeighbours=5,hash=1478885765},RegionSection{sectionCoordinate=[21, 1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=284867684},RegionSection{sectionCoordinate=[25, 0],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1894249292},RegionSection{sectionCoordinate=[16, 2],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1563532153},RegionSection{sectionCoordinate=[14, -4],chunkCount=18,chunksBitset=0000000000000000000000000000000000070007000000000007000700070007,nonEmptyNeighbours=3,hash=896762739},RegionSection{sectionCoordinate=[27, 2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1890521125},RegionSection{sectionCoordinate=[18, -1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1067315439},RegionSection{sectionCoordinate=[10, 0],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=1848004150},RegionSection{sectionCoordinate=[13, 2],chunkCount=32,chunksBitset=c000c000c000c000c000c000c000c000c000c000c000c000c000c000c000c000,nonEmptyNeighbours=5,hash=1197944986},RegionSection{sectionCoordinate=[26, 3],chunkCount=84,chunksBitset=007f007f007f007f007f007f007f007f007f007f007f007f0000000000000000,nonEmptyNeighbours=3,hash=1329671787},RegionSection{sectionCoordinate=[26, -1],chunkCount=63,chunksBitset=0000000000000000007f000000000000007f007f007f007f007f007f007f007f,nonEmptyNeighbours=3,hash=529249764},RegionSection{sectionCoordinate=[22, 3],chunkCount=168,chunksBitset=fffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffcfffc0000000000000000,nonEmptyNeighbours=3,hash=1132466141},RegionSection{sectionCoordinate=[11, -1],chunkCount=70,chunksBitset=ffc0ffc0ffc0ffc00000ffc0ffc0ffc000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1025316055},RegionSection{sectionCoordinate=[15, 1],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=2070497129},RegionSection{sectionCoordinate=[21, 0],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=965732725},RegionSection{sectionCoordinate=[16, 5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=144013537},RegionSection{sectionCoordinate=[14, -5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=2058549118},RegionSection{sectionCoordinate=[27, -1],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=794623827},RegionSection{sectionCoordinate=[14, 0],chunkCount=200,chunksBitset=ff80ff00ff000000fff8fff8ffe0ffe0fffffffffffffffeffffffffffffffff,nonEmptyNeighbours=7,hash=515880926},RegionSection{sectionCoordinate=[16, 0],chunkCount=240,chunksBitset=ffffffffffff0000ffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=5,hash=1480405309},RegionSection{sectionCoordinate=[23, 2],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=895038531},RegionSection{sectionCoordinate=[26, -2],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=2109207516},RegionSection{sectionCoordinate=[12, 3],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=508934899},RegionSection{sectionCoordinate=[17, 5],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=3,hash=1716173655},RegionSection{sectionCoordinate=[18, 4],chunkCount=57,chunksBitset=007f007f007f007f003f007f007f007f00000000000000030000000000000000,nonEmptyNeighbours=3,hash=793822429},RegionSection{sectionCoordinate=[18, 2],chunkCount=240,chunksBitset=7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff7fff,nonEmptyNeighbours=5,hash=1398216280},RegionSection{sectionCoordinate=[27, 4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=1,hash=297547517},RegionSection{sectionCoordinate=[22, -1],chunkCount=126,chunksBitset=0000000000000000fffc000000000000fffcfffcfffcfffcfffcfffcfffcfffc,nonEmptyNeighbours=3,hash=571315227},RegionSection{sectionCoordinate=[13, -1],chunkCount=112,chunksBitset=ffffffffffffffff0000ffffffffffff00000000000000000000000000000000,nonEmptyNeighbours=7,hash=198363819},RegionSection{sectionCoordinate=[17, 1],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1616701535},RegionSection{sectionCoordinate=[24, 1],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=279388535},RegionSection{sectionCoordinate=[22, 4],chunkCount=0,chunksBitset=0000000000000000000000000000000000000000000000000000000000000000,nonEmptyNeighbours=2,hash=1581564468},RegionSection{sectionCoordinate=[13, -3],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1138678981},RegionSection{sectionCoordinate=[23, 0],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1153948401},RegionSection{sectionCoordinate=[12, -2],chunkCount=256,chunksBitset=ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,nonEmptyNeighbours=8,hash=1833101191}]}
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.EntityPlayer.dn()" because "player" is null
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:167) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:74) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:266) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:828) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:660) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:984) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:384) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:434) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:40:47] [Region Scheduler Thread #3/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Uncaught exception in tick thread "Region Scheduler Thread #3"
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.EntityPlayer.dn()" because "player" is null
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:167) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:74) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:266) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:828) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:660) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:984) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:384) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:434) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.2.jar:git-Luminol-"909b208"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:40:47] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[14:40:47] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[14:40:47] [Region shutdown thread/INFO]: Stopping server

**Comment by xiaoluofa** [comment]
![23581bb773d56550c84e65db85059645](https://github.com/sjavi4/PlayerDoll/assets/75927411/4fab219d-8d66-4744-b97c-7bd7ded98b58)

**Comment by sjavi4** [comment]
v1.24.1 https://modrinth.com/plugin/playerdoll/version/V5XCIpqo
please have a look

**Comment by xiaoluofa** [comment]
> v1.24.1 https://modrinth.com/plugin/playerdoll/version/V5XCIpqo please have a look

It works properly and there is no problem! Thank you for your work!
