### ISSUE TITLE
FOLIA ERROR

### ISSUE THREAD

**Issue by xiaoluofa** [sjavi4/PlayerDoll#27]
[20:57:24 INFO]: _Kamisat0Ayaka_ issued server command: /doll spawn 123
[20:57:24 INFO]: [PlayerDoll] Doll Config [-123] Saved Successfully.
[20:57:24 INFO]: [PlayerDoll] Fake Client connected to Server
[20:57:24 INFO]: [PlayerDoll] Client Connected
[20:57:25 INFO]: [FeatherMorph] Soulhomelamp joined with API version 11
[20:57:25 INFO]: [PlayerDoll] Found Connection
[20:57:25 INFO]: [PlayerDoll] Setup Compression for Fake Client
[20:57:25 INFO]: [PlayerDoll] Fake Client Handle Client GameProfile
[20:57:26 INFO]: [PlayerDoll] Handle Fake Client Configuration
[20:57:26 INFO]: [PlayerDoll] Doll Joined Successfully, Suspend Server-side Packet Sending.
[20:57:26 INFO]: M1917_MG_ > 6
[20:57:26 INFO]: -123[/127.0.0.1:2549] logged in with entity id 12830 at ([world]8.5, 66.0, 4044.5)
[20:57:27 ERROR]: Thread Region Scheduler Thread #10 failed main thread check: Ticking map player in incorrect region
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at net.minecraft.world.level.saveddata.maps.MapItemSavedData.tickCarriedBy(MapItemSavedData.java:268) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:137) ~[?:?]
        at net.minecraft.server.level.ChunkMap.foliaEntityTrackerTick(ChunkMap.java:1099) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1119) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:447) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:946) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1808) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:451) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1647) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.20.4.jar:git-L
uminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.
jar:git-Luminol-"01abc6c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j
ar:git-Luminol-"01abc6c"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:57:27 INFO]: [SeeMore] Set view distance of -123 to 8 (client view distance is 2).
[20:57:27 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #2 centered at chunk [-22, 242] in world 'world' failed to t
ick:
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1820) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:451) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1647) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[luminol-1.20.4.jar:git-L
uminol-"01abc6c"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.
jar:git-Luminol-"01abc6c"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.j
ar:git-Luminol-"01abc6c"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Ticking map player in incorrect region
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        at net.minecraft.world.level.saveddata.maps.MapItemSavedData.tickCarriedBy(MapItemSavedData.java:268) ~[?:?]
        at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:137) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.foliaEntityTrackerTick(ChunkTracker.java:1099) ~[?:?]
        at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:1119) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:447) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:946) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1808) ~[luminol-1.20.4.jar:git-Luminol-"01abc6c"]
        ... 6 more
[20:57:27 INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[20:57:27 INFO]: [RegionShutdownThread] Scheduler halted

**Comment by sjavi4** [comment]
Could not replicate this problem.
I used the same server luminol and spawn the doll, nothing went wrong.
Is there some differences between your test suit and the server.

**Comment by xiaoluofa** [comment]
> Could not replicate this problem. I used the same server luminol and spawn the doll, nothing went wrong. Is there some differences between your test suit and the server.

I used the same plug-in to test

**Comment by xiaoluofa** [comment]
I can't reproduce it on my test server either.

**Comment by xiaoluofa** [comment]
I asked the author of luminol, maybe there is an answer.

**Comment by xiaoluofa** [comment]
The author is not sure. Thank you for your work.

**Comment by sjavi4** [comment]
> The author is not sure. Thank you for your work.

thanks for reporting it
