### ISSUE TITLE
doll wont stay online

### ISSUE THREAD

**Issue by bovinespongiformflu** [sjavi4/PlayerDoll#34]
doll creation works fine. on previous versions the doll could join with no issue but would be disconnected after a couple days due to chat acknowledgements. with the latest version. joining doesnt work properly, they come online and then leave immediately. console shows the following

[01:54:16 INFO]: -sandy joined the game
[01:54:16 INFO]: -sandy[/127.0.0.1:35992] logged in with entity id 6108 at ([world]-25.984434864147136, -51.5, -23595.215762953132)
[01:54:16 ERROR]: Could not pass event DollJoinEvent to PlayerDoll v1.27
java.lang.UnsupportedOperationException: Must use teleportAsync while in region threading
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1312) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1261) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.teleport(CraftEntity.java:226) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.teleport(CraftEntity.java:296) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at me.autobot.playerdoll.EventListener.DollJoin.onDollJoin(DollJoin.java:32) ~[PlayerDoll-1.27.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor83.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:git-Folia-"25ee657"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.autobot.playerdoll.v1_20_R3.player.ServerDoll.setup(ServerDoll.java:47) ~[PlayerDoll-1.27.jar:?]
        at me.autobot.playerdoll.v1_20_R3.Network.ServerPacketHandler.ServerConfigurationListener.lambda$handleConfigurationFinished$0(ServerConfigurationListener.java:31) ~[PlayerDoll-1.27.jar:?]
        at me.autobot.playerdoll.folia.FoliaScheduler.lambda$globalTaskDelayed$0(FoliaScheduler.java:18) ~[PlayerDoll-1.27.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:54:16 WARN]: [io.papermc.paper.threadedregions.RegionizedWorldData] Failed to handle packet for /127.0.0.1:35992
java.lang.NullPointerException: Cannot read field "dollRealPlayerTickUpdate" because the return value of "me.autobot.playerdoll.v1_20_R3.player.ServerDoll.getDollConfig()" is null
        at me.autobot.playerdoll.v1_20_R3.Network.ServerPacketHandler.ServerGamePlayListener.e(ServerGamePlayListener.java:19) ~[PlayerDoll-1.27.jar:?]
        at net.minecraft.network.Connection.tick(Connection.java:648) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:529) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1843) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1657) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"25ee657"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[01:54:16 INFO]: [PlayerDoll] Client Disconnected, Internal server error
[01:54:16 INFO]: [PlayerDoll] Client Disconnected, End of stream
[01:54:16 INFO]: -sandy lost connection: Internal server error
[01:54:16 INFO]: [voicechat] Disconnecting client -sandy
[01:54:16 INFO]: -sandy left the game

**Comment by sjavi4** [comment]
Known issue, please wait for new verison

**Comment by sjavi4** [comment]
@bovinespongiformflu 
A new Version has released, please check https://modrinth.com/plugin/playerdoll/version/1.28Dev
