### ISSUE TITLE
Folia issues

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#35]
[19:59:48 INFO]: -cirno_saikou[/127.0.0.1:55573] logged in with entity id 2228 at ([world]7312.5, 88.0, -3379.5)
[19:59:49 ERROR]: Could not pass event DollJoinEvent to PlayerDoll v1.27
java.lang.UnsupportedOperationException: Must use teleportAsync while in region threading
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1314) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1263) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.teleport(CraftEntity.java:230) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.teleport(CraftEntity.java:300) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at me.autobot.playerdoll.EventListener.DollJoin.onDollJoin(DollJoin.java:32) ~[PlayerDoll-1.27.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:git-Luminol-"391ba7a"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at me.autobot.playerdoll.v1_20_R3.player.ServerDoll.setup(ServerDoll.java:47) ~[PlayerDoll-1.27.jar:?]
        at me.autobot.playerdoll.v1_20_R3.Network.ServerPacketHandler.ServerConfigurationListener.lambda$handleConfigurationFinished$0(ServerConfigurationListener.j
ava:31) ~[PlayerDoll-1.27.jar:?]
        at me.autobot.playerdoll.folia.FoliaScheduler.lambda$globalTaskDelayed$0(FoliaScheduler.java:18) ~[PlayerDoll-1.27.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[luminol-1.20.4.jar:?
]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:294) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a
"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"
]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:59:49 WARN]: [io.papermc.paper.threadedregions.RegionizedWorldData] Failed to handle packet for /127.0.0.1:55573
java.lang.NullPointerException: Cannot read field "dollRealPlayerTickUpdate" because the return value of "me.autobot.playerdoll.v1_20_R3.player.ServerDoll.getDollCo
nfig()" is null
        at me.autobot.playerdoll.v1_20_R3.Network.ServerPacketHandler.ServerGamePlayListener.e(ServerGamePlayListener.java:19) ~[PlayerDoll-1.27.jar:?]
        at net.minecraft.network.Connection.tick(Connection.java:657) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:529) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1870) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a
"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"
]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:59:49 INFO]: [PlayerDoll] Client Disconnected, Internal server error
[19:59:49 INFO]: [PlayerDoll] Client Disconnected, End of stream
[19:59:49 INFO]: -cirno_saikou lost connection: Internal server error

**Comment by sjavi4** [comment]
Known issue, please wait for new verison

**Comment by sjavi4** [comment]
@1264175987 
A new Version has released, please check https://modrinth.com/plugin/playerdoll/version/1.28Dev

**Comment by 1264175987** [comment]
It's not working.
[10:08:57 INFO]: Cirno_Saikou issued server command: /doll create 1 Cirno_Saikou
[10:08:57 INFO]: [PlayerDoll] Doll Config [-1] Saved Successfully
It's nothing happend after i use the command.
If do "/doll menu 1" after create ,it will say can't find target.
test on Folia 1.20.4

**Comment by sjavi4** [comment]
> It's nothing happend after i use the command.
> If do "/doll menu 1" after create ,it will say can't find target.
> test on Folia 1.20.4

1. please check the plugin config to see the ip and port are correct
2. do you modified any server settings? like server port, bungeecord mode
3. is there any plugin installed

there should be some connection status being logged when the connection is success (finding correct ip and port)

**Comment by sjavi4** [comment]
> It's not working. [10:08:57 INFO]: Cirno_Saikou issued server command: /doll create 1 Cirno_Saikou [10:08:57 INFO]: [PlayerDoll] Doll Config [-1] Saved Successfully It's nothing happend after i use the command. If do "/doll menu 1" after create ,it will say can't find target. test on Folia 1.20.4

After create, you have to /doll spawn <target> to let the doll connect to the world

**Comment by 1264175987** [comment]
Thanks for your help, it works
