### ISSUE TITLE
cant spawn a player

### ISSUE THREAD

**Issue by Shotgn995533** [sjavi4/PlayerDoll#4]
I can create a player without problems (im on 1.20.2 with version 1.8) but when i spawn it, it gives me this exception
16:09:36 INFO]: Shotgun995533 issued server command: /doll chunkloader spawn
[16:09:36 WARN]: java.lang.reflect.InvocationTargetException
[16:09:36 WARN]: at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(Unknown Source)
[16:09:36 WARN]: at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[16:09:36 WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[16:09:36 WARN]: at PlayerDoll-1.8-1.20.2.jar//me.autobot.playerdoll.newCommand.CommandHandler.execute(CommandHandler.java:46)
[16:09:36 WARN]: at PlayerDoll-1.8-1.20.2.jar//me.autobot.playerdoll.newCommand.CommandHandler.onCommand(CommandHandler.java:23)
[16:09:36 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[16:09:36 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[16:09:36 WARN]: at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:989)
[16:09:36 WARN]: at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)

**Comment by sjavi4** [comment]
Please download v1.9.
This issue has been fixed.
https://github.com/sjavi4/PlayerDoll/releases/tag/v1.9
https://modrinth.com/plugin/playerdoll/version/1.9

**Comment by Shotgn995533** [comment]
ok i didnt see the version on modrinth thx
