### ISSUE TITLE
Folia issues

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#40]
Some times Server will stop by watchdog when use command "doll despawn" or "doll tp"
plugin version : 1.29  1.28
folia version : 1.20.4

I contacted the Luminol author, he said may be there is a problem with the doll deletion logic not with the server, so i tried to contacted with you.

This is the server log:
[2024-06-23-8.log](https://github.com/user-attachments/files/15957026/2024-06-23-8.log)

**Comment by sjavi4** [comment]
```Java
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at net.minecraft.world.level.saveddata.maps.MapItemSavedData.tickCarriedBy(MapItemSavedData.java:268)
```

I checked the Server code, is there any map item in nearby or being held by players? It seems like it make something wrong while ticking the map item (player icon on map).


The code snippet
```Java
public void tickCarriedBy(Player entityhuman, ItemStack itemstack) {
       TickThread.ensureTickThread(player, "Ticking map player in incorrect region");
       ...
       for(int i = 0; i < this.carriedBy.size(); ++i) {
            HoldingPlayer worldmap_worldmaphumantracker1 = (HoldingPlayer)this.carriedBy.get(i);
            String s = worldmap_worldmaphumantracker1.player.getName().getString();
            if (worldmap_worldmaphumantracker1.player.isRemoved() || !worldmap_worldmaphumantracker1.player.getInventory().contains(itemstack) && !itemstack.isFramed()) {
                ...
            } else if (!itemstack.isFramed() && worldmap_worldmaphumantracker1.player.level().dimension() == this.dimension && this.trackingPosition) {
                Here ? >> this.addDecoration(Type.PLAYER, worldmap_worldmaphumantracker1.player.level(), s, worldmap_worldmaphumantracker1.player.getX(), worldmap_worldmaphumantracker1.player.getZ(), (double)worldmap_worldmaphumantracker1.player.getYRot(), (Component)null);
            }
        }
        Here ? >> if (stack.F() && this.l) {
            ...
        }
    }
```

**Comment by 1264175987** [comment]
The player holds a menu(a cookie).Nothing else

**Comment by sjavi4** [comment]
How about the chunks nearby, is there any hanging maps?

**Comment by 1264175987** [comment]
I'm sorry I didn't pay too much attention with it.There were a lot of players when the server was down.So I just removed the plugin when the server shut down for the third time.

**Comment by sjavi4** [comment]
Would you like to test this version?
https://github.com/sjavi4/PlayerDoll/releases/tag/v1.29.2

**Comment by 1264175987** [comment]
Server went down immediately when using command "despawn"

**Comment by 1264175987** [comment]
> Server went down immediately when using command "despawn"

But I had no issues when testing in a blank server.It doesn't matter if you use official folia or luminol.
Thanks for your help


This is the server log:
[14:49:10] [Region Scheduler Thread #7/INFO]: Cirno_Saikou issued server command: /doll despawn -Cirno_Saikou
[14:49:10] [Region Scheduler Thread #7/INFO]: [PlayerDoll] Connection Closed Successfully
[14:49:10] [Region Scheduler Thread #7/INFO]: [PlayerDoll] Doll -Cirno_Saikou Despawned by Cirno_Saikou
[14:49:10] [Thread-253/WARN]: [PlayerDoll] Client ShutDown
[14:49:10] [Region Scheduler Thread #7/INFO]: -Cirno_Saikou lost connection: Disconnected
[14:49:10] [Folia Async Scheduler Thread #170/INFO]: [HuskSync] [DEBUG] [49:10.491] [-Cirno_Saikou] Set SERVER_SWITCH key to Redis
[14:49:10] [Region Scheduler Thread #7/INFO]: [PlayerDoll] Doll Config [-Cirno_Saikou] Saved Successfully
[14:49:10] [Region Scheduler Thread #7/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #9696 centered at chunk [-193, 129] in world 'world' failed to tick:
java.lang.NullPointerException: Cannot read field "f" because "pos" is null
	at io.papermc.paper.util.CoordinateUtils.getChunkKey(CoordinateUtils.java:29) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.removeTicketAtLevel(ChunkHolderManager.java:676) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at net.minecraft.server.level.DistanceManager.removeTicket(DistanceManager.java:96) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.removeTicketAtLevel(ServerChunkCache.java:145) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.cleanUpConnection(RegionizedWorldData.java:503) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:520) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1870) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"391ba7a"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[14:49:10] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[14:49:10] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[14:49:10] [Region shutdown thread/INFO]: Stopping server
