### ISSUE TITLE
Cannot getEntities asynchronously

### ISSUE THREAD

**Issue by milu2048** [sjavi4/PlayerDoll#48]
**versions:**
PlayerDoll-1.30

**Most likely causes:**
The playerdoll is not allowed to use names such as "6". It is recommended to disable the generation of doll with such names.

**log:**
_[20:53:05] [Region Scheduler Thread #0/INFO]: <name> issued server command: /doll attack -6<playerdoll name> interval 50
[20:53:07] [Region Scheduler Thread #0/ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Cannot getEntities asynchronously
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:85) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.world.level.Level.getEntities(Level.java:1566) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.v1_20_R4.carpetmod.NMSActionPackPlayer.getEntities(NMSActionPackPlayer.java:41) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.Tracer.rayTraceEntities(Tracer.java:198) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.Tracer.rayTraceEntities(Tracer.java:190) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.Tracer.rayTrace(Tracer.java:171) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.getTarget(EntityPlayerActionPack.java:273) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack$ActionType$2.execute(EntityPlayerActionPack.java:393) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack$Action.tick(EntityPlayerActionPack.java:647) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.onUpdate(EntityPlayerActionPack.java:236) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.v1_20_R4.player.ExtServerPlayer.updateActionPack(ExtServerPlayer.java:40) ~[PlayerDoll-1.30.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.runOneTask(RegionizedServer.java:162) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.drainTasks(RegionizedServer.java:152) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:147) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:53:07] [Region Scheduler Thread #0/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #-1 centered at chunk null in world 'null' failed to tick:
java.lang.IllegalStateException: Cannot getEntities asynchronously
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:86) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.world.level.Level.getEntities(Level.java:1566) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.v1_20_R4.carpetmod.NMSActionPackPlayer.getEntities(NMSActionPackPlayer.java:41) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.Tracer.rayTraceEntities(Tracer.java:198) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.Tracer.rayTraceEntities(Tracer.java:190) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.Tracer.rayTrace(Tracer.java:171) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.getTarget(EntityPlayerActionPack.java:273) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack$ActionType$2.execute(EntityPlayerActionPack.java:393) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack$Action.tick(EntityPlayerActionPack.java:647) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.onUpdate(EntityPlayerActionPack.java:236) ~[PlayerDoll-1.30.jar:?]
	at PlayerDoll-1.30.jar/me.autobot.playerdoll.v1_20_R4.player.ExtServerPlayer.updateActionPack(ExtServerPlayer.java:40) ~[PlayerDoll-1.30.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.runOneTask(RegionizedServer.java:162) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.drainTasks(RegionizedServer.java:152) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:147) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[20:53:07] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[20:53:07] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[20:53:07] [Region shutdown thread/INFO]: Stopping server_

**Comment by sjavi4** [comment]
do 2 digit number or pure number name also cause this problem?

**Comment by milu2048** [comment]
I reproduced this type of error with doll named "111", which immediately reported an error causing the server to crash

**Comment by milu2048** [comment]
Almost any pure number can cause an error

**Comment by sjavi4** [comment]
any details on Server Jar and Proxy? I tried to repeat the process on 1.20.6 Folia with/without BungeeCord but nothing happened.

**Comment by milu2048** [comment]
I used modrinth to download playerdoll 1.30.0 in the experimental 1.20.6 Folia version (no proxy) with this error

**Comment by milu2048** [comment]
I used the playerdoll 1.30.0 plugin downloaded from the modrinth website to get this error in the experimental 1.20.6 Folia version (without an agent)

**Comment by sjavi4** [comment]
Do you enabled `real player tick action` in Doll setting?

**Comment by milu2048** [comment]
Oh, thank you for your help. There are no errors after opening

**Comment by sjavi4** [comment]
So your crash is because of Disabling the setting?
I tried in Folia, enabling the setting will cause the crash

**Comment by milu2048** [comment]
No, I solved it by turning it on. I use LuckPerms plug-in opened the "playerdoll. Globalflag. Real_player_tick_action" after calling name for "123" doll, found not collapse

**Comment by sjavi4** [comment]
did you try it on the latest folia and plugin version?

**Comment by milu2048** [comment]
I didn't get any more bugs when I tested with the new version, maybe it has been fixed, thank you for your work
