### ISSUE TITLE
failed to tick chunk

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#56]
**Describe the bug**
Invalid move player packet received

 - 1.20.4
 - 1.31.1
 - uminol-1.20.4-bundler-d753f16.jar
 - Velocity
 - Server Log

[22:53:25] [Region Scheduler Thread #0/INFO]: QeveryoneR issued server command: /doll spawn -Moonlight__06
[22:53:25] [Netty Server IO #3/INFO]: [PlayerDoll] Doll Joined Successfully, Suspend Server-side Packet Sending.
[22:53:25] [Folia Async Scheduler Thread Timer/INFO]: [HuskSync] [DEBUG] [53:25.831] [-Moonlight__06] DATA_CHECKOUT key not set on Redis
[22:53:25] [Folia Async Scheduler Thread Timer/INFO]: [HuskSync] [DEBUG] [53:25.832] [-Moonlight__06] Set DATA_CHECKOUT key to/from Redis
[22:53:25] [Folia Async Scheduler Thread Timer/INFO]: [HuskSync] [DEBUG] [53:25.833] [-Moonlight__06] Waiting for LATEST_SNAPSHOT key from Redis
[22:53:25] [Region Scheduler Thread #9/INFO]: [PlayerDoll] Config [PERMISSION] Found, Load From Exist.
[22:53:25] [Region Scheduler Thread #11/INFO]: -Moonlight__06[/127.0.0.1:56680] logged in with entity id 321953 at ([world_nether]-5108.699999988079, 148.0, -6738.583405002044)
[22:53:25] [Region Scheduler Thread #9/INFO]: [PlayerDoll] Config [PERMISSION] Saved Successfully
[22:53:25] [Folia Async Scheduler Thread #201/INFO]: [HuskSync] [DEBUG] [53:25.870] Applying snapshot (60602335) to -Moonlight__06 (cause: Synchronized)
[22:53:26] [Region Scheduler Thread #3/INFO]: -Moonlight__06 lost connection: Invalid move player packet received
[22:53:26] [Thread-290/INFO]: [PlayerDoll] Client Disconnected (play phase)
[22:53:26] [Thread-290/INFO]: [PlayerDoll] Client Connection Closed
[22:53:26] [Thread-290/INFO]: [PlayerDoll] Connection Closed Successfully
[22:53:26] [Thread-290/INFO]: [PlayerDoll] Client Thread End
[22:53:26] [Region Scheduler Thread #3/INFO]: [PlayerDoll] Doll Config [-Moonlight__06] Saved Successfully
[22:53:26] [Folia Async Scheduler Thread #26/INFO]: [HuskSync] [DEBUG] [53:26.425] [-Moonlight__06] Set LATEST_SNAPSHOT key on Redis
[22:53:26] [Folia Async Scheduler Thread #26/INFO]: [HuskSync] [DEBUG] [53:26.426] [-Moonlight__06] Removed DATA_CHECKOUT key to/from Redis
[22:53:26] [Region Scheduler Thread #3/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #354 centered at chunk [-264, 103] in world 'world' failed to tick:
java.lang.NullPointerException: Cannot read field "f" because "pos" is null
	at io.papermc.paper.util.CoordinateUtils.getChunkKey(CoordinateUtils.java:29) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.removeTicketAtLevel(ChunkHolderManager.java:676) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.level.DistanceManager.removeTicket(DistanceManager.java:96) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.removeTicketAtLevel(ServerChunkCache.java:145) ~[?:?]
	at io.papermc.paper.threadedregions.RegionizedWorldData.cleanUpConnection(RegionizedWorldData.java:503) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.RegionizedWorldData.tickConnections(RegionizedWorldData.java:520) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1870) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:53:26] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[22:53:26] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[22:53:26] [Region shutdown thread/INFO]: Stopping server

**Comment by sjavi4** [comment]
Does `Invalid move player packet received` pop up in every spawn attempt?

**Comment by 1264175987** [comment]
No, not every time

**Comment by sjavi4** [comment]
Should Fixed.

https://modrinth.com/plugin/playerdoll/version/1.32

https://github.com/sjavi4/PlayerDoll/commit/d0bf5681d95c2eeeb929bd426f2cef5aae58b52f
https://github.com/sjavi4/PlayerDoll/commit/b7ca6c75f8f84070d63f95892325dfaaf93e0c9a

**Comment by zhjc2021** [comment]
> No, not every time



> Did #50 already solved?
> 
> #56 should Fixed.
> 
> https://modrinth.com/plugin/playerdoll/version/1.32
> 
> [d0bf568](https://github.com/sjavi4/PlayerDoll/commit/d0bf5681d95c2eeeb929bd426f2cef5aae58b52f) [b7ca6c7](https://github.com/sjavi4/PlayerDoll/commit/b7ca6c75f8f84070d63f95892325dfaaf93e0c9a)

There's a new problem in this version
server crushed when i slain a doll

[21:56:12] [Region Scheduler Thread #10/INFO]: -Moonlight__02 was slain by zhjc
[21:56:12] [Region Scheduler Thread #10/ERROR]: Thread Region Scheduler Thread #10 failed main thread check: Ticking map player in incorrect region
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.world.level.saveddata.maps.MapItemSavedData.tickCarriedBy(MapItemSavedData.java:268) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:137) ~[?:?]
	at net.minecraft.server.level.ChunkMap.foliaEntityTrackerTick(ChunkMap.java:1099) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1119) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:447) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:946) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1845) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:56:12] [Region Scheduler Thread #3/INFO]: [PlayerDoll] Doll Respawn
[21:56:12] [Region Scheduler Thread #3/INFO]: [PlayerDoll] Connection Closed Successfully
[21:56:12] [Thread-267/WARN]: [PlayerDoll] Client ShutDown
[21:56:12] [Region Scheduler Thread #3/INFO]: -Moonlight__02 lost connection: Disconnected
[21:56:12] [Region Scheduler Thread #3/INFO]: [PlayerDoll] Doll Config [-Moonlight__02] Saved Successfully
[21:56:12] [DefaultDispatcher-worker-5/INFO]: [bakamc-folia] 玩家加退出游戏
[21:56:12] [Folia Async Scheduler Thread #8760/INFO]: [HuskSync] [DEBUG] [56:12.461] [-Moonlight__02] Set LATEST_SNAPSHOT key on Redis
[21:56:12] [Folia Async Scheduler Thread #8760/INFO]: [HuskSync] [DEBUG] [56:12.462] [-Moonlight__02] Removed DATA_CHECKOUT key to/from Redis
[21:56:12] [Region Scheduler Thread #10/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #323986 centered at chunk [-200, 93] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1857) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Ticking map player in incorrect region
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.world.level.saveddata.maps.MapItemSavedData.tickCarriedBy(MapItemSavedData.java:268) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:137) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.foliaEntityTrackerTick(ChunkTracker.java:1099) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:1119) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:447) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:946) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1845) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	... 6 more
[21:56:12] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[21:56:12] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[21:56:12] [Region shutdown thread/INFO]: Stopping server

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/releases/tag/v1.32.1

Please try this version

**Comment by zhjc2021** [comment]
> https://github.com/sjavi4/PlayerDoll/releases/tag/v1.32.1
> 
> Please try this version

this version also has bug

[16:04:19] [Region Scheduler Thread #7/INFO]: -moonlight_06 was slain by QeveryoneR
[16:04:20] [Region Scheduler Thread #2/INFO]: brbsjl issued server command: /bal
[16:04:20] [Region Scheduler Thread #2/INFO]: [PlayerDoll] Doll Respawn
[16:04:20] [Region Scheduler Thread #11/INFO]: [PlayerDoll] Connection Closed Successfully
[16:04:20] [Thread-284/WARN]: [PlayerDoll] Client ShutDown
[16:04:20] [Region Scheduler Thread #11/INFO]: -moonlight_06 lost connection: Disconnected
[16:04:20] [Region Scheduler Thread #11/INFO]: [PlayerDoll] Doll Config [-moonlight_06] Saved Successfully
[16:04:20] [DefaultDispatcher-worker-1/INFO]: [bakamc-folia] 玩家加退出游戏
[16:04:20] [Region Scheduler Thread #7/ERROR]: Thread Region Scheduler Thread #7 failed main thread check: Ticking map player in incorrect region
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.world.level.saveddata.maps.MapItemSavedData.tickCarriedBy(MapItemSavedData.java:268) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:137) ~[?:?]
	at net.minecraft.server.level.ChunkMap.foliaEntityTrackerTick(ChunkMap.java:1099) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1119) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:447) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:946) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1845) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[16:04:20] [Folia Async Scheduler Thread #148/INFO]: [HuskSync] [DEBUG] [04:20.804] [-moonlight_06] Set LATEST_SNAPSHOT key on Redis
[16:04:20] [Folia Async Scheduler Thread #148/INFO]: [HuskSync] [DEBUG] [04:20.805] [-moonlight_06] Removed DATA_CHECKOUT key to/from Redis
[16:04:20] [Region Scheduler Thread #7/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #644 centered at chunk [-169, 128] in world 'world' failed to tick:
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1857) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1670) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Ticking map player in incorrect region
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	at net.minecraft.world.level.saveddata.maps.MapItemSavedData.tickCarriedBy(MapItemSavedData.java:268) ~[?:?]
	at net.minecraft.server.level.ServerEntity.sendChanges(ServerEntity.java:137) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.foliaEntityTrackerTick(ChunkTracker.java:1099) ~[?:?]
	at net.minecraft.server.level.ChunkTracker.tick(ChunkTracker.java:1119) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:447) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:946) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1845) ~[luminol-1.20.4.jar:git-Luminol-"d753f16"]
	... 6 more
[16:04:20] [Region shutdown thread/INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[16:04:20] [Region shutdown thread/INFO]: [RegionShutdownThread] Scheduler halted
[16:04:20] [Region shutdown thread/INFO]: Stopping server

**Comment by sjavi4** [comment]
This crash only appear in Folia/Luminol servers when Doll is being **moved outside of nearby regions** while the `chunk region` contains _Hanging Maps of that region_.

Temporarily please don't let player spawn / tp / kill / despawn / entering portals if the region has Hanging Maps

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/releases/tag/v1.32.2

Please try this version and test if any problems.

**Comment by sjavi4** [comment]
If you are not very rely on the feature of Map cursor and tracking.
A temporary solution is available: Goto `paper-world-defaults.yml` and set the value of `item-frame-cursor-update-interval` to 0
