### ISSUE TITLE
Plugin Doesn't work on ShreddedPaper

### ISSUE THREAD

**Issue by dusieq95** [sjavi4/PlayerDoll#57]
**Describe the bug**
Plugin doesn't run on ShreddedPaper

 - Minecraft 1.20.6
 - Plugin Version - 1.31.1
 - shreddedpaper-1.20.6-78
 - Proxy name in use
 - Server Log 
 
 `[02:10:13 INFO]: [PlayerDoll] Enabling PlayerDoll v1.31
[02:10:13 INFO]: [PlayerDoll] Config [BASIC] Found, Load From Exist.
[02:10:13 WARN]: [PlayerDoll] Config [Basic Config] version does not Match the Latest (26). Default value of missing keys will be used.
[02:10:13 INFO]: [PlayerDoll] Config [Basic Config] version updated.
[02:10:13 INFO]: [PlayerDoll] Config [BASIC] Saved Successfully
[02:10:13 INFO]: [PlayerDoll] Config did not assign Server Mod. Detecting...
[02:10:13 ERROR]: Error occurred while enabling PlayerDoll v1.31 (Is it up to date?)
java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.orElseThrow(Optional.java:377) ~[?:?]
        at PlayerDoll-1.31.1.jar/me.autobot.playerdoll.util.ReflectionUtil.initialFoliaRegionizedServer(ReflectionUtil.java:117) ~[PlayerDoll-1.31.1.jar:?]
        at PlayerDoll-1.31.1.jar/me.autobot.playerdoll.PlayerDoll.initServerBranch(PlayerDoll.java:198) ~[PlayerDoll-1.31.1.jar:?]
        at PlayerDoll-1.31.1.jar/me.autobot.playerdoll.PlayerDoll.onEnable(PlayerDoll.java:99) ~[PlayerDoll-1.31.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[shreddedpaper-1.20.6.jar:1.20.6-78-244dd22]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[shreddedpaper-1.20.6.jar:1.20.6-78-244dd22]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:645) ~[shreddedpaper-1.20.6.jar:1.20.6-78-244dd22]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:593) ~[shreddedpaper-1.20.6.jar:1.20.6-78-244dd22]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:684) ~[shreddedpaper-1.20.6.jar:1.20.6-78-244dd22]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:446) ~[shreddedpaper-1.20.6.jar:1.20.6-78-244dd22]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[shreddedpaper-1.20.6.jar:1.20.6-78-244dd22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1159) ~[shreddedpaper-1.20.6.jar:1.20.6-78-244dd22]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[shreddedpaper-1.20.6.jar:1.20.6-78-244dd22]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[02:10:13 INFO]: [PlayerDoll] Disabling PlayerDoll v1.31`

**To Reproduce**
1. Run Server
2. See Logs in console

**Expected behavior**

**Setting of Doll**
Doll's current setting. From config or GUI. This might be helpful when clarifing the problem
i.e. Hostility = true / Gravity: false

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Context in code (If applicable)**

**Additional context**

**Comment by sjavi4** [comment]
What is the upstream of ShreddedPaper, like Paper or Folia.

If the plugin cannot detect the mod of server in-use automatically, you can try to manually assign the `server-mod` in config.yml
(assign the most suitable one "Spigot" / "PaperSeries" / "Folia")

**Comment by sjavi4** [comment]
ShreddedPaper is a bit different from Folia, it might take times.
I will do some investigations, if not too difficult, than i will make a support.

**Comment by sjavi4** [comment]
You can try to manually assign value to `server-mod` in config.yml to see if there is chance to make the plugin run.

**Comment by dusieq95** [comment]
Yeah, after i put `PaperSeries` in `server-mod` it works just fine :)
