### ISSUE TITLE
Cant create doll on 1.20.2 ? 

### ISSUE THREAD

**Issue by vxkShelby** [sjavi4/PlayerDoll#7]
plugin is loaded successfuly....

[10:31:17 INFO]: vxkShelby issued server command: /doll Johny create

[10:31:17 WARN]: java.lang.reflect.InvocationTargetException

[10:31:17 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [10:31:17 WARN]: at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) [10:31:17 WARN]: at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[10:31:17 WARN]: at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) [10:31:17 WARN]: at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) [10:31:17 WARN]: at PlayerDoll-1.12.jar//me.autobot.playerdoll.newCommand.CommandHandler.execute(CommandHandler.java:46)

[10:31:17 WARN]: at PlayerDoll-1.12.jar//me.autobot.playerdoll.newCommand.CommandHandler.onCommand(CommandHandler.java:23)

[10:31:17 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)

[10:31:17 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)

[10:31:17 WARN]: at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:991)

[10:31:17 WARN]: at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)

[10:31:17 WARN]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)

[10:31:17 WARN]: at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:330)

[10:31:17 WARN]: at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:314)

[10:31:17 WARN]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2208)

[10:31:17 WARN]: at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$19(PlayerConnection.java:2168)

[10:31:17 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)

[10:31:17 WARN]: at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)

[10:31:17 WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)

[10:31:17 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)

[10:31:17 WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)

[10:31:17 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)

[10:31:17 WARN]: at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)

[10:31:17 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)

[10:31:17 WARN]: at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)

[10:31:17 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)

[10:31:17 WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)

[10:31:17 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1371)

[10:31:17 WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)

[10:31:17 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)

[10:31:17 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)

[10:31:17 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "org.bukkit.configuration.file.YamlConfiguration.getString(String)" is null

[10:31:17 WARN]: at PlayerDoll-1.12.jar//me.autobot.playerdoll.newCommand.SubCommand.checkPermission(SubCommand.java:39)

[10:31:17 WARN]: at PlayerDoll-1.12.jar//me.autobot.playerdoll.newCommand.Execute.create.<init>(create.java:34)

[10:31:17 WARN]: ... 31 more

**Comment by sjavi4** [comment]
Fixed [v1.13](https://modrinth.com/plugin/playerdoll/version/1.13)
- Doll creation error when player is not Server Operator
