### ISSUE TITLE
Dolls can't automatically join in the server when server starts  java.EOFException

### ISSUE THREAD

**Issue by LYXOfficial** [sjavi4/PlayerDoll#70]
**Describe the bug**

The dolls can't automatically join in the server when server starts,and there are some logs when i'm closing the server:

```
[03:21:25 WARN]: [PlayerDoll] Error caught on Client
[03:21:25 WARN]: java.io.EOFException
[03:21:25 WARN]:     at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:297)
[03:21:25 WARN]:     at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
[03:21:25 INFO]: [PlayerDoll] Connection Closed Successfully
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.packet.Packets.readVarInt(Packets.java:68)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.readPacketCompressed(SocketReader.java:228)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.run(SocketReader.java:92)
[03:21:25 WARN]: java.net.SocketException: Socket is closed
[03:21:25 WARN]:     at java.base/java.net.Socket.shutdownInput(Socket.java:1756)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.close(SocketReader.java:131)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.run(SocketReader.java:114)
[03:21:25 WARN]: [PlayerDoll] Error caught on Closing Connection
[03:21:25 INFO]: [PlayerDoll] Client Thread End
[03:21:25 INFO]: [PlayerDoll] Connection Closed Successfully
[03:21:25 WARN]: [PlayerDoll] Error caught on Client
[03:21:25 WARN]: java.io.EOFException
[03:21:25 WARN]:     at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:297)
[03:21:25 WARN]:     at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.packet.Packets.readVarInt(Packets.java:68)
[03:21:25 INFO]: [PlayerDoll] Connection Closed Successfully
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.readPacketCompressed(SocketReader.java:228)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.run(SocketReader.java:92)
[03:21:25 WARN]: java.net.SocketException: Socket is closed
[03:21:25 INFO]: [PlayerDoll] Connection Closed Successfully
[03:21:25 WARN]:     at java.base/java.net.Socket.shutdownInput(Socket.java:1756)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.close(SocketReader.java:131)
[03:21:25 WARN]: [PlayerDoll] Error caught on Client
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.run(SocketReader.java:114)
[03:21:25 WARN]: [PlayerDoll] Error caught on Closing Connection
[03:21:25 INFO]: [PlayerDoll] Client Thread End
[03:21:25 INFO]: [PlayerDoll] Connection Closed Successfully
[03:21:25 WARN]: java.io.EOFException
[03:21:25 WARN]:     at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:297)
[03:21:25 WARN]:     at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.packet.Packets.readVarInt(Packets.java:68)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.readPacketCompressed(SocketReader.java:228)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.run(SocketReader.java:92)
[03:21:25 WARN]: java.net.SocketException: Socket is closed
[03:21:25 WARN]:     at java.base/java.net.Socket.shutdownInput(Socket.java:1756)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.close(SocketReader.java:131)
[03:21:25 WARN]:     at PlayerDoll-1.32.jar//me.autobot.playerdoll.socket.io.SocketReader.run(SocketReader.java:114)
[03:21:25 WARN]: [PlayerDoll] Error caught on Closing Connection
```

 - Minecraft Version 1.20.6
 - Plugin Version 1.32
 - Server Jar name and version paper-1.20.6-148.jar 

**Expected behavior**
The dolls should automaticlly join in the server when the server starts.

**Setting of Doll**
all of the dolls in the server set join_at_start=true

**Comment by sjavi4** [comment]
Would you test again in a clean environment with newly generated Doll config?

**Comment by LYXOfficial** [comment]
> Would you test again in a clean environment with newly generated Doll config?

That's works well,but when i don't know why does it can't work in our server.

Oh, it worked well before the problems in our server world, but once someone mistakenly used/kill @ e, and then I replaced the entities and DIM-1/entities folders from a previous backup. After that, the doll no longer joined normally

**Comment by sjavi4** [comment]
I have no idea about this, maybe the simplest solution is to re-create those dolls.
