### ISSUE TITLE
all doll cannot spawn when restart the server，only one。

### ISSUE THREAD

**Issue by JackHanner** [sjavi4/PlayerDoll#71]
hello，my server core is folia 1.20.6 with playerdoll 1.32 。

I set up 4 dolls to join at server startup, but only one doll can join at a time, and it's a random one. I am certain that I have set the maximum number of players to join simultaneously to 10 (max joins per tick: 10). The following is the startup log
```
[21:59:25 信息]: [PlayerDoll] Wait for Login Listener
[21:59:25 信息]: [PlayerDoll] Wait for Login Listener
[21:59:25 信息]: [PlayerDoll] Wait for Login Listener
[21:59:25 信息]: [PlayerDoll] Wait for Login Listener
[21:59:25 信息]: [PlayerDoll] Wait for Login Listener
[21:59:25 警告]: java.net.SocketTimeoutException: Connect timed out
[21:59:25 警告]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[21:59:25 警告]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
[21:59:25 警告]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[21:59:25 警告]:        at java.base/java.net.Socket.connect(Socket.java:751)
[21:59:25 警告]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[21:59:25 警告]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[21:59:25 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[21:59:25 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[21:59:25 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[21:59:25 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
[21:59:25 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[21:59:25 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[21:59:25 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[21:59:25 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[21:59:25 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[21:59:25 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[21:59:25 警告]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[21:59:25 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.versionFetcher.VersionFetcher.getDataFromUrl(VersionFetcher.java:22)
[21:59:25 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.versionFetcher.ModrinthVersionFetcher.fetchNewestVersion(ModrinthVersionFetcher.java:22)
[21:59:25 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.versionFetcher.MasterVersionFetcher.fetchNewestVersion(MasterVersionFetcher.java:24)
[21:59:25 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.VersionConfig.usingLatestVersion(VersionConfig.java:60)
[21:59:25 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.VersionConfig.checkVersionAndDisplay(VersionConfig.java:39)
[21:59:25 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancynpcs.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:34)
[21:59:25 警告]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source)
[21:59:25 警告]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[21:59:25 警告]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[21:59:25 警告]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:59:25 警告]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:59:25 警告]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[21:59:25 警告]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[21:59:25 警告]:        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:440)
[21:59:25 警告]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.lambda$handleConfigurationFinished$2(ServerConfigurationPacketListenerImpl.java:183)
[21:59:25 警告]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504)
[21:59:25 警告]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434)
[21:59:25 警告]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263)
[21:59:25 警告]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1676)
[21:59:25 警告]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408)
[21:59:25 警告]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[21:59:25 警告]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[21:59:25 警告]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:59:26 警告]: java.net.SocketTimeoutException: Connect timed out
[21:59:26 警告]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[21:59:26 警告]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
[21:59:26 警告]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[21:59:26 警告]:        at java.base/java.net.Socket.connect(Socket.java:751)
[21:59:26 警告]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[21:59:26 警告]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[21:59:26 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[21:59:26 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[21:59:26 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.versionFetcher.VersionFetcher.getDataFromUrl(VersionFetcher.java:22)
[21:59:26 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.versionFetcher.ReposiliteVersionFetcher.fetchNewestVersion(ReposiliteVersionFetcher.java:22)
[21:59:26 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.versionFetcher.MasterVersionFetcher.fetchNewestVersion(MasterVersionFetcher.java:24)
[21:59:26 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.VersionConfig.usingLatestVersion(VersionConfig.java:60)
[21:59:26 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancylib.VersionConfig.checkVersionAndDisplay(VersionConfig.java:39)
[21:59:26 警告]:        at FancyNpcs-2.2.1.jar//de.oliver.fancynpcs.listeners.PlayerJoinListener.onPlayerJoin(PlayerJoinListener.java:34)
[21:59:26 警告]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor26.execute(Unknown Source)
[21:59:26 警告]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[21:59:26 警告]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[21:59:26 警告]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:59:26 警告]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[21:59:26 警告]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[21:59:26 警告]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[21:59:26 警告]:        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:440)
[21:59:26 警告]:        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.lambda$handleConfigurationFinished$2(ServerConfigurationPacketListenerImpl.java:183)
[21:59:26 警告]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504)
[21:59:26 警告]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434)
[21:59:26 警告]:        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263)
[21:59:26 警告]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1676)
[21:59:26 警告]:        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408)
[21:59:26 警告]:        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404)
[21:59:26 警告]:        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525)
[21:59:26 警告]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:59:26 信息]: Farmer (formerly known as -Farmer) joined the game
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 信息]: Farmer[/172.18.0.42:36498] logged in with entity id 2 at ([world]-556.6999999880791, 66.0, -255.69999998807907)
[21:59:26 警告]: java.net.SocketTimeoutException: Connect timed out
[21:59:26 警告]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[21:59:26 警告]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
[21:59:26 警告]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[21:59:26 警告]:        at java.base/java.net.Socket.connect(Socket.java:751)
[21:59:26 警告]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[21:59:26 警告]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[21:59:26 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[21:59:26 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.versionFetcher.VersionFetcher.getDataFromUrl(VersionFetcher.java:22)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.versionFetcher.HangarVersionFetcher.fetchNewestVersion(HangarVersionFetcher.java:19)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.versionFetcher.MasterVersionFetcher.fetchNewestVersion(MasterVersionFetcher.java:24)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.VersionConfig.usingLatestVersion(VersionConfig.java:60)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.VersionConfig.checkVersionAndDisplay(VersionConfig.java:39)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancyholograms.listeners.PlayerListener.lambda$onJoin$0(PlayerListener.java:26)
[21:59:26 警告]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:59:26 警告]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:59:26 警告]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:59:26 警告]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:59:26 警告]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:59:26 警告]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 信息]: [PlayerDoll] Wait for Login Listener
[21:59:26 警告]: java.net.SocketTimeoutException: Connect timed out
[21:59:26 警告]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[21:59:26 警告]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
[21:59:26 警告]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[21:59:26 警告]:        at java.base/java.net.Socket.connect(Socket.java:751)
[21:59:26 警告]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[21:59:26 警告]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[21:59:26 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[21:59:26 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.versionFetcher.VersionFetcher.getDataFromUrl(VersionFetcher.java:22)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.versionFetcher.ModrinthVersionFetcher.fetchNewestVersion(ModrinthVersionFetcher.java:22)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.versionFetcher.MasterVersionFetcher.fetchNewestVersion(MasterVersionFetcher.java:24)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.VersionConfig.usingLatestVersion(VersionConfig.java:60)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.VersionConfig.checkVersionAndDisplay(VersionConfig.java:39)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancyholograms.listeners.PlayerListener.lambda$onJoin$0(PlayerListener.java:26)
[21:59:26 警告]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:59:26 警告]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:59:26 警告]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:59:26 警告]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:59:26 警告]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:59:26 警告]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:59:26 警告]: java.net.SocketTimeoutException: Connect timed out
[21:59:26 警告]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
[21:59:26 警告]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
[21:59:26 警告]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[21:59:26 警告]:        at java.base/java.net.Socket.connect(Socket.java:751)
[21:59:26 警告]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[21:59:26 警告]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[21:59:26 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[21:59:26 警告]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:377)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1237)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1123)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1675)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[21:59:26 警告]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:223)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.versionFetcher.VersionFetcher.getDataFromUrl(VersionFetcher.java:22)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.versionFetcher.ReposiliteVersionFetcher.fetchNewestVersion(ReposiliteVersionFetcher.java:22)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.versionFetcher.MasterVersionFetcher.fetchNewestVersion(MasterVersionFetcher.java:24)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.VersionConfig.usingLatestVersion(VersionConfig.java:60)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancylib.VersionConfig.checkVersionAndDisplay(VersionConfig.java:39)
[21:59:26 警告]:        at FancyHolograms-2.3.0.jar//de.oliver.fancyholograms.listeners.PlayerListener.lambda$onJoin$0(PlayerListener.java:26)
[21:59:26 警告]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[21:59:26 警告]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[21:59:26 警告]:        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
[21:59:26 警告]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[21:59:26 警告]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[21:59:26 警告]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:27 信息]: [PlayerDoll] Wait for Login Listener
[21:59:28 信息]: [PlayerDoll] Client wait Too Long
[21:59:28 信息]: [PlayerDoll] Client wait Too Long
[21:59:28 信息]: [PlayerDoll] Client wait Too Long
[21:59:28 信息]: [PlayerDoll] Client wait Too Long
[21:59:28 信息]: [PlayerDoll] Client wait Too Long
[21:59:28 警告]: [PlayerDoll] Doll Farmer failed to Join, Please Try again Later
[21:59:28 警告]: [PlayerDoll] Doll Sand_end failed to Join, Please Try again Later
[21:59:28 警告]: [PlayerDoll] Doll tttest failed to Join, Please Try again Later
[21:59:28 警告]: [PlayerDoll] Doll Meat failed to Join, Please Try again Later
[21:59:28 信息]: [PlayerDoll] Client Connection Closed
[21:59:28 警告]: [PlayerDoll] Doll Sand failed to Join, Please Try again Later
[21:59:28 信息]: [PlayerDoll] Client Connection Closed
[21:59:28 信息]: [PlayerDoll] Client Connection Closed
[21:59:28 信息]: [PlayerDoll] Client Connection Closed
[21:59:28 信息]: [PlayerDoll] Client Connection Closed
[21:59:28 信息]: [PlayerDoll] Connection Closed Successfully
[21:59:28 信息]: [PlayerDoll] Connection Closed Successfully
[21:59:28 信息]: [PlayerDoll] Connection Closed Successfully
[21:59:28 信息]: [PlayerDoll] Connection Closed Successfully
[21:59:28 信息]: [PlayerDoll] Connection Closed Successfully
[21:59:28 信息]: [PlayerDoll] Client Thread End
[21:59:28 信息]: [PlayerDoll] Client Thread End
[21:59:28 信息]: [PlayerDoll] Client Thread End
[21:59:28 信息]: [PlayerDoll] Client Thread End
[21:59:28 信息]: [PlayerDoll] Client Thread End
[21:59:31 信息]: [ChatColorHandler] Found MiniMessage in Server. MiniMessage support enabled.
[22:04:47 信息]: There are 1 of a max of 21 players online: Farmer
```

**Comment by sjavi4** [comment]
Any proxy in use? Like BungeeCord.

Max-Join-Per-Tick should be a lagacy config setting, and auto join have no use for that.

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/1.34

The delay should help

**Comment by JackHanner** [comment]
> 有没有在使用的代理？就像蹦极绳一样。
> 
> Max-Join-Per-Tick 应该是一个滞后配置设置，自动加入对此没有用处。

no

**Comment by JackHanner** [comment]
> https://modrinth.com/plugin/playerdoll/version/1.34
> 
> 延迟应该会有所帮助
There is still no improvement. I am using genuine verification, so it should not be a verification issue. Otherwise, there would not have been only one doll joining, and it should have been impossible to join at all. I guess it might be a whitelist issue. Before restarting, I added all the dolls to the whitelist, but after restarting, using whitelist add @ a still prompted that the addition was successful, instead of the player already existing in the whitelist

**Comment by JackHanner** [comment]
> https://modrinth.com/plugin/playerdoll/version/1.34
> 
> 延迟应该会有所帮助

There is still no improvement. I am using online mode, so it should not be a verification issue. Otherwise, there would not have been only one doll joining, and it should have been impossible to join at all. I guess it might be a whitelist issue. Before restarting, I added all the dolls to the whitelist, but after restarting, using whitelist add @ a still prompted that the addition was successful, instead of the player already existing in the whitelist
