### ISSUE TITLE
Open the backpack across the latitude and throw it out ,the item will disappear.

### ISSUE THREAD

**Issue by milu2048** [sjavi4/PlayerDoll#73]
**Describe the bug**
Open the backpack across the latitude and throw it out ,the item will disappear.

 - 1.20.6
 - v1.33.1
 - Folia 1.20.6 [Experiments]
 - no Proxy
 - Server Log
```
[01:21:54] [Region Scheduler Thread #0/INFO]: CengjingMiLu issued server command: /doll inv Ceng1
[01:21:56] [Region Scheduler Thread #0/INFO]: CengjingMiLu issued server command: /playerdoll:doll drop Ceng1 0
[01:21:56] [Region Scheduler Thread #0/ERROR]: Thread Region Scheduler Thread #0 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftItem.getHandle(CraftItem.java:30) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftItem.getItemStack(CraftItem.java:36) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at 【核心保护】CoreProtect-22.4.jar/net.coreprotect.listener.player.PlayerDropItemListener.onPlayerDropItem(PlayerDropItemListener.java:40) ~[【核心保护】CoreProtect-22.4.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.player.Player.drop(Player.java:774) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2979) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.world.entity.player.Player.drop(Player.java:721) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:3070) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftHumanEntity.dropItem(CraftHumanEntity.java:771) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.dropItemFromSlot(EntityPlayerActionPack.java:283) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.drop(EntityPlayerActionPack.java:300) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.command.subcommand.actionpack.ActionDrop.execute(ActionDrop.java:28) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.command.subcommand.actionpack.ActionDrop.onCommand(ActionDrop.java:64) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.DollCommandSource.execute(DollCommandSource.java:64) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.CommandBuilder.performCommandSelf(CommandBuilder.java:714) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.CommandBuilder.actionDropExecute(CommandBuilder.java:722) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.CommandBuilder.lambda$static$25(CommandBuilder.java:133) ~[【假人】PlayerDoll-1.33.jar:?]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2254) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2531) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftPlayer.chat(CraftPlayer.java:753) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.menu.DollBackpackMenu.dropSlot(DollBackpackMenu.java:243) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.menu.DollBackpackMenu.onClick(DollBackpackMenu.java:75) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.GUIManager.click(GUIManager.java:32) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.MenuWatcher.onClick(MenuWatcher.java:17) ~[【假人】PlayerDoll-1.33.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3265) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:57) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:85) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1688) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:21:56] [Region Scheduler Thread #0/ERROR]: Could not pass event PlayerDropItemEvent to CoreProtect v22.4
java.lang.IllegalStateException: Accessing entity state off owning region's thread
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftItem.getHandle(CraftItem.java:30) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftItem.getItemStack(CraftItem.java:36) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at 【核心保护】CoreProtect-22.4.jar/net.coreprotect.listener.player.PlayerDropItemListener.onPlayerDropItem(PlayerDropItemListener.java:40) ~[【核心保护】CoreProtect-22.4.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.player.Player.drop(Player.java:774) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2979) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.world.entity.player.Player.drop(Player.java:721) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:3070) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftHumanEntity.dropItem(CraftHumanEntity.java:771) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.dropItemFromSlot(EntityPlayerActionPack.java:283) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.drop(EntityPlayerActionPack.java:300) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.command.subcommand.actionpack.ActionDrop.execute(ActionDrop.java:28) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.command.subcommand.actionpack.ActionDrop.onCommand(ActionDrop.java:64) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.DollCommandSource.execute(DollCommandSource.java:64) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.CommandBuilder.performCommandSelf(CommandBuilder.java:714) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.CommandBuilder.actionDropExecute(CommandBuilder.java:722) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.CommandBuilder.lambda$static$25(CommandBuilder.java:133) ~[【假人】PlayerDoll-1.33.jar:?]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2254) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2531) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftPlayer.chat(CraftPlayer.java:753) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.menu.DollBackpackMenu.dropSlot(DollBackpackMenu.java:243) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.menu.DollBackpackMenu.onClick(DollBackpackMenu.java:75) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.GUIManager.click(GUIManager.java:32) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.MenuWatcher.onClick(MenuWatcher.java:17) ~[【假人】PlayerDoll-1.33.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3265) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:57) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:85) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1688) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:21:56] [Region Scheduler Thread #0/ERROR]: Command exception: /playerdoll:doll drop Ceng1 0
java.lang.IllegalStateException: World mismatch: expected FOLIA多线程纯生存服务器 but got FOLIA多线程纯生存服务器_nether
	at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:213) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1886) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1814) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1809) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2984) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.world.entity.player.Player.drop(Player.java:721) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:3070) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftHumanEntity.dropItem(CraftHumanEntity.java:771) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.dropItemFromSlot(EntityPlayerActionPack.java:283) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.drop(EntityPlayerActionPack.java:300) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.command.subcommand.actionpack.ActionDrop.execute(ActionDrop.java:28) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.command.subcommand.actionpack.ActionDrop.onCommand(ActionDrop.java:64) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.DollCommandSource.execute(DollCommandSource.java:64) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.CommandBuilder.performCommandSelf(CommandBuilder.java:714) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.CommandBuilder.actionDropExecute(CommandBuilder.java:722) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.brigadier.CommandBuilder.lambda$static$25(CommandBuilder.java:133) ~[【假人】PlayerDoll-1.33.jar:?]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2254) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2531) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.craftbukkit.entity.CraftPlayer.chat(CraftPlayer.java:753) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.menu.DollBackpackMenu.dropSlot(DollBackpackMenu.java:243) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.menu.DollBackpackMenu.onClick(DollBackpackMenu.java:75) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.GUIManager.click(GUIManager.java:32) ~[【假人】PlayerDoll-1.33.jar:?]
	at 【假人】PlayerDoll-1.33.jar/me.autobot.playerdoll.gui.MenuWatcher.onClick(MenuWatcher.java:17) ~[【假人】PlayerDoll-1.33.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[folia-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3265) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:57) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:85) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1688) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-5-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:22:07] [Region Scheduler Thread #0/INFO]: CengjingMiLu issued server command: /playerdoll:doll menu Ceng1
[01:22:09] [Region Scheduler Thread #0/INFO]: CengjingMiLu issued server command: /playerdoll:doll inv Ceng1
``` 

**To Reproduce**
1. Go to Nether
2. Use /doll inv <dollname>
3. Use 'Q' in item

**Expected behavior**
To disable opening the backpack press 'Q' or other methods

**Setting of Doll**
no

**Screenshots or Videos**

https://github.com/user-attachments/assets/08ea08be-3997-4e51-8870-2414981cd53e

**Related Setup (If your problem is related to 3rd parties)**
- add plugin 'CoreProtect-22.4' [It also appeared in the log]

**Comment by sjavi4** [comment]
Should be fixed next version

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/1.34
