### ISSUE TITLE
Dolls cannot be used

### ISSUE THREAD

**Issue by achenrhyc** [sjavi4/PlayerDoll#84]
**Describe the bug**

 - Minecraft Version:paper1.21.1
 - Plugin Version:1.35.4
 - Server Jar name and version
 - Proxy name in use
 - Server Log

**To Reproduce**

**Expected behavior**

**Server Setting**
State if you changed some uncommon settings
i.e. Whitelist, Online-mode, specific server-mod settings

**Setting of Doll**
Doll's current setting. From config or GUI. This might be helpful when clarifing the problem
i.e. Hostility = true / Gravity: false

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.

**Related Setup (If your problem is related to 3rd parties)**
- Resource Packs
- Server Properties
- Others

**Context in code (If applicable)**

**Additional context**

**Comment by sjavi4** [comment]
Would you like to provide more context?

**Comment by minrog666** [comment]
> Would you like to provide more context?

When using the command `/doll use test continuous`，some times the console will appear this error and the doll disappears (but still in the server)

```
[15:31:32 ERROR]: Entity threw exception at world:7937.477716408838,38.0,-5844.175536324886
java.lang.ClassCastException: class org.bukkit.craftbukkit.entity.CraftPlayer cannot be cast to class net.minecraft.world.entity.Entity (org.bukkit.craftbukkit.entity.CraftPlayer and net.minecraft.world.entity.Entity are in unnamed module of loader java.net.URLClassLoader @68de145)
        at PlayerDoll-1.35.jar/me.autobot.playerdoll.v1_21_R1.wrapper.NMSEntity.getCraftEntity(NMSEntity.java:19) ~[PlayerDoll-1.35.jar:?]
        at PlayerDoll-1.35.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack$ActionType$1.execute(EntityPlayerActionPack.java:372) ~[PlayerDoll-1.35.jar:?]
        at PlayerDoll-1.35.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack$Action.tick(EntityPlayerActionPack.java:799) ~[PlayerDoll-1.35.jar:?]
        at PlayerDoll-1.35.jar/me.autobot.playerdoll.carpetmod.EntityPlayerActionPack.onUpdate(EntityPlayerActionPack.java:241) ~[PlayerDoll-1.35.jar:?]
        at PlayerDoll-1.35.jar/me.autobot.playerdoll.v1_21_R1.player.ExtServerPlayer.updateActionPack(ExtServerPlayer.java:40) ~[PlayerDoll-1.35.jar:?]
        at PlayerDoll-1.35.jar/me.autobot.playerdoll.v1_21_R1.player.ServerDoll.beforeTick(ServerDoll.java:91) ~[PlayerDoll-1.35.jar:?]
        at PlayerDoll-1.35.jar/me.autobot.playerdoll.v1_21_R1.player.ExtServerPlayer.tick(ExtServerPlayer.java:47) ~[PlayerDoll-1.35.jar:?]
        at PlayerDoll-1.35.jar/me.autobot.playerdoll.v1_21_R1.player.ServerDoll.tick(ServerDoll.java:131) ~[PlayerDoll-1.35.jar:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1245) ~[leaves-1.21.1.jar:1.21.1-52-e199edf]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:732) ~[leaves-1.21.1.jar:1.21.1-52-e199edf]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[leaves-1.21.1.jar:1.21.1-52-e199edf]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:709) ~[leaves-1.21.1.jar:1.21.1-52-e199edf]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1794) ~[leaves-1.21.1.jar:1.21.1-52-e199edf]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[leaves-1.21.1.jar:1.21.1-52-e199edf]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[leaves-1.21.1.jar:1.21.1-52-e199edf]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[leaves-1.21.1.jar:1.21.1-52-e199edf]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[leaves-1.21.1.jar:1.21.1-52-e199edf]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
