### ISSUE TITLE
Spawning a playerdoll issue

### ISSUE THREAD

**Issue by Technologx** [sjavi4/PlayerDoll#88]
**Describe the bug**

 - Minecraft Version : 1.21
 - Plugin Version : 1.36
 - Server Jar name and version pupur - 1.21
 - Proxy name in use default
 - Server Log

[17:56:56 ERROR]: Command exception: /doll spawn Xavier
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:483) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:89) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:83) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:164) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:148) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at PlayerDoll-1.36.jar/me.autobot.playerdoll.netty.DollConnection.connect(DollConnection.java:119) ~[PlayerDoll-1.36.jar:?]
        at PlayerDoll-1.36.jar/me.autobot.playerdoll.command.subcommand.Spawn.execute(Spawn.java:44) ~[PlayerDoll-1.36.jar:?]
        at PlayerDoll-1.36.jar/me.autobot.playerdoll.command.subcommand.Spawn.onCommand(Spawn.java:93) ~[PlayerDoll-1.36.jar:?]
        at PlayerDoll-1.36.jar/me.autobot.playerdoll.brigadier.DollCommandSource.execute(DollCommandSource.java:66) ~[PlayerDoll-1.36.jar:?]
        at PlayerDoll-1.36.jar/me.autobot.playerdoll.brigadier.CommandBuilder.lambda$static$141(CommandBuilder.java:580) ~[PlayerDoll-1.36.jar:?]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:451) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:358) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.commands.Commands.performCommand(Commands.java:340) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2226) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2200) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2280-930003b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2280-930003b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**To Reproduce**
doll create Xavier DarkFenyx
doll spawn Xavier

**Expected behavior**
I expect the doll to spawn for me to control it

**Server Setting**
N/A

**Setting of Doll**
Default

**Screenshots or Videos**
![image](https://github.com/user-attachments/assets/68ffabe0-7dcb-4b3e-94f3-c82c160de3e0)

**Related Setup (If your problem is related to 3rd parties)**
N/A

**Context in code (If applicable)**

**Additional context**

**Comment by Technologx** [comment]
Well I'm removing this plugin

**Comment by sjavi4** [comment]
About this, i cannot reproduce this in my pc at all.
After searching in the internet, there is no solid way to fix it either.


Here is the very limited thing that I can do to help with.
Would you test this plugin and locate any problems?
https://github.com/sjavi4/PlayerDoll/releases/tag/dev_1.36.1
