### ISSUE TITLE
Error in pipeline when spawning dolls.

### ISSUE THREAD

**Issue by Boryte** [sjavi4/PlayerDoll#92]
**Describe the bug**

 - 1.20.4
 - 1.3.6
 - Purpur 2176
 - Velocity
 
 `[18:28:33 INFO]: [PlayerDoll] Config [FLAG] Saved Successfully
[18:28:33 INFO]: [PlayerDoll] Doll Config [penis] Saved Successfully
[18:28:33 WARN]: [PlayerDoll] Config [LANGUAGE] Not Up to Date, Generate From Resource.
[18:28:33 WARN]: [PlayerDoll] Config [default] Not Up to Date, Please Check Language File.
[18:28:33 INFO]: [PlayerDoll] Config [LANGUAGE] Saved Successfully
[18:28:33 INFO]: [PlayerDoll] Config [default] Found, Load From Exist.
[18:28:38 INFO]: Boryte issued server command: /doll spawn penis
[18:28:38 INFO]: [PlayerDoll] Doll client -penis started
[18:28:38 WARN]: [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalMonitorStateException: current thread is not owner
        at java.lang.Object.wait0(Native Method) ~[?:?]
        at java.lang.Object.wait(Object.java:366) ~[?:?]
        at me.autobot.playerdoll.netty.handler.HandshakeHandler.channelActive(HandshakeHandler.java:49) ~[PlayerDoll-1.36.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:29:08 INFO]: [PlayerDoll] Doll client -penis ended`

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/releases/tag/dev_1.36.2

Does this version solved the problem
