### ISSUE TITLE
Can't open the menu after restarting the server when Join at Start is enabled for the dummy

### ISSUE THREAD

**Issue by AllCheeks** [sjavi4/PlayerDoll#98]
**Describe the bug**

 - Minecraft Version 1.20.1
 - Plugin Version 1.24.1
 
Can't open the menu after restarting the server when Join at Start is enabled for the dummy

[00:53:25 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'doll' in plugin PlayerDoll v1.24
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[forge-1.20.1-47.3.11-universal.jar%23305!/:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:147) ~[forge-1.20.1-47.3.11-universal.jar%23305!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:890) ~[forge-1.20.1-47.3.11-universal.jar%23305!/:997de31d-ddc9a2dad-d2eba2c8-47.1.106]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2926) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2945) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.chat(CraftPlayer.java:408) ~[forge-1.20.1-47.3.11-universal.jar%23305!/:?]
        at me.autobot.playerdoll.Events.PlayerInteractDollEvent.onPlayerRightClick(PlayerInteractDollEvent.java:26) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[forge-1.20.1-47.3.11-universal.jar%23305!/:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge-1.20.1-47.3.11-universal.jar%23305!/:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:604) ~[forge-1.20.1-47.3.11-universal.jar%23305!/:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:588) ~[forge-1.20.1-47.3.11-universal.jar%23305!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_143678_(ServerGamePacketListenerImpl.java:2174) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$1.m_142299_(ServerGamePacketListenerImpl.java:2219) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$InteractionAction.m_142457_(ServerboundInteractPacket.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_179617_(ServerboundInteractPacket.java:75) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6946_(ServerGamePacketListenerImpl.java:2163) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:62) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.m_5797_(ServerboundInteractPacket.java:12) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1026) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:176) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1009) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1003) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:989) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:914) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23300!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.autobot.playerdoll.GUIs.Doll.DollInvStorage.getInfoPage()" because the return value of "java.util.Map.get(Object)" is null
        at me.autobot.playerdoll.Command.SubCommands.Menu.<init>(Menu.java:11) ~[?:?]
        at me.autobot.playerdoll.Command.CommandType$16.execute(CommandType.java:250) ~[?:?]
        at me.autobot.playerdoll.Command.CommandHelper.onCommand(CommandHelper.java:35) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[forge-1.20.1-47.3.11-universal.jar%23305!/:

如何修复？

**Comment by sjavi4** [comment]
v1.24.1 is no longer supported, i would suggust you upgrade to Minecraft 1.20.2 and download the latest plugin.
The code structure has changed a lot between v1.24.1 to now, and i forgot the old logics.
If you are going to fix by yourself, you can check the source code https://github.com/sjavi4/PlayerDoll/tree/v1.24.1
