### ISSUE TITLE
PlayerDoll is not work,can't spawn doll

### ISSUE THREAD

**Issue by hetaoawa** [sjavi4/PlayerDoll#99]
**Describe the bug**

 - Minecraft Version : 1.20.4
 - Plugin Version : 1.37  BungeeCord : 1.33-BungeeCord
 - Server Jar name and version : Purpur 1.20.4-2176
 - Proxy name in use  : BungeeCord
 - Server Log
 
```
[21:03:53] [Server thread/INFO]: hetao_awa issued server command: /doll create HSDSDS
[21:03:53] [Server thread/INFO]: [PlayerDoll] Doll Config [HSDSDS] Saved Successfully
[21:04:11] [Server thread/INFO]: hetao_awa issued server command: /doll spawn HSDSDS
[21:04:11] [Netty Doll #3/INFO]: [PlayerDoll] Doll client -HSDSDS started
[21:04:11] [Netty Doll #3/WARN]: [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalMonitorStateException: current thread is not owner
	at java.lang.Object.wait0(Native Method) ~[?:?]
	at java.lang.Object.wait(Object.java:366) ~[?:?]
	at me.autobot.playerdoll.netty.handler.HandshakeHandler.channelActive(HandshakeHandler.java:49) ~[PlayerDoll-1.37.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:04:11] [Server thread/INFO]: [PlayerDoll] Plugin Start Handshake
[21:04:23] [Server thread/INFO]: hetao_awa issued server command: /doll spawn -HSDSDS
[21:04:23] [Netty Doll #4/INFO]: [PlayerDoll] Doll client -HSDSDS started
[21:04:23] [Netty Doll #4/WARN]: [io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalMonitorStateException: current thread is not owner
	at java.lang.Object.wait0(Native Method) ~[?:?]
	at java.lang.Object.wait(Object.java:366) ~[?:?]
	at me.autobot.playerdoll.netty.handler.HandshakeHandler.channelActive(HandshakeHandler.java:49) ~[PlayerDoll-1.37.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:260) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:231) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:258) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:238) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[21:04:23] [Server thread/INFO]: [PlayerDoll] Plugin Start Handshake
[21:04:38] [Server thread/INFO]: hetao_awa issued server command: /doll remove HSDSDS
[21:04:41] [Netty Epoll Server IO #9/WARN]: io.netty.handler.timeout.ReadTimeoutException
[21:04:41] [Netty Doll #3/INFO]: [PlayerDoll] Doll client -HSDSDS ended
[21:04:53] [Netty Epoll Server IO #10/WARN]: io.netty.handler.timeout.ReadTimeoutException
[21:04:53] [Netty Doll #4/INFO]: [PlayerDoll] Doll client -HSDSDS ended

``` 

**To Reproduce**
1. Use Minecraft Purpur 1.20.4-21764 Plugin Version : 1.37  BungeeCord : 1.33-BungeeCord
2. /doll create HSDSDS
3. /doll spawn HSDSDS

**Expected behavior**
Generate Bot normally .

**Server Setting**
Use BungeeCord , Server whitelist = True , BugeeCord Online-Mode = True

**Setting of Doll**
Doll's current setting. From config or GUI. This might be helpful when clarifing the problem
```
server-mod: 'PaperSeries'

force-proxy-ip: false

proxy-ip: 0.0.0.0

proxy-port: 14040

``` 

**Additional context**
Try using other versions of the plugin, but either no response or this error message appears.

**Comment by sjavi4** [comment]
Well, Bungeecord is a bit troublesome to handling the connection, and I am planning to stop supporting it.
If you are fine with Velocity, i would suggest you to use it, since both should work the same.
